name: Separate Gradle Jobs
on:
  push:
    branches: main
    paths-ignore:
      - "*.md"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: 7.4
            arguments: assemble --info
      - uses: actions/upload-artifact@v4
        with:
          name: gradle-build-artifact
          path: build/
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: gradle-build-artifact
          path: build/
      - run: ls -l build/
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: 7.4
            arguments: test --info