name: Separate Gradle Jobs
on:
  push:
    branches: main
    paths-ignore:
      - "*.md"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        if: false
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: 7.4
            arguments: assemble --info --build-cache 
      - uses: actions/upload-artifact@v4
        with:
          name: gradle-build-artifact
          path: build/
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        if: false
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/download-artifact@v4
        with:
          name: gradle-build-artifact
          path: build/
      - run: ls -l build/
      - name: Gradle Test
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: 7.4
            arguments: test --info --build-cache 
      - run: ls -l .
      - run: ls -l .gradle/
      - run: ls -l .gradle/buildOutputCleanup/
