name: Trigger Downstreams
on:
  push:
    branches: main
    paths-ignore:
      - "*.md"
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0, 42] # one should succeed, the other fail
    steps:
      - name: Workflow Dispatch
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: MisterErwin
          repo: GithubActionTest2
          github_token: ${{ secrets.PAT }}
          client_payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "fail": "${{matrix.returncode}}"}'
          workflow_file_name: wfdispatch.yml
