name: Trigger Downstreams
on:
  push:
    branches: main
    paths-ignore:
      - "*.md"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: MisterErwin
          repo: GithubActionTest2
          github_token: ${{ secrets.PAT }}
          #event-type: trigger_downstream
          client_payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
